version: '3.9'

services:
  subtrack-be:
    build:
      context: ./subtrack-be
      dockerfile: Dockerfile
    container_name: subtrack-be
    env_file:
      - ./subtrack-be/be.env
    ports:
      - "8080:8080"
    networks:
      - subtrack-net
    restart: unless-stopped

networks:
  subtrack-net:
    driver: bridge
